<center> <h2>Machine Learning With Python: Save And Load Trained Model</h2></center>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [6]:
model.predict([[5000]])

array([859554.79452055])

<h2>Save Model To a File Using Python Pickle</h2>

In [7]:
import pickle

In [8]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

<b>Load Saved Model</b>

In [9]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [10]:
mp.coef_

array([135.78767123])

In [11]:
mp.intercept_

180616.43835616432

In [12]:
mp.predict([[5000]])

array([859554.79452055])

<h2>Save Trained Model Using joblib</h2>

In [13]:
import joblib

In [14]:
joblib.dump(model, 'model_joblib')

['model_joblib']

<b>Load Saved Model</b>

In [15]:
mj = joblib.load('model_joblib')

In [16]:
mj.coef_

array([135.78767123])

In [17]:
mj.intercept_

180616.43835616432

In [18]:
mj.predict([[5000]])

array([859554.79452055])